name = "newsnow1"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "f12f8be1-b8f7-4baf-898f-aa6443cb5aa6"
